### ISSUE TITLE
"lake" app installed

### ISSUE THREAD

**Issue by danames** [BYU-Hydroinformatics/warehouse#2]
I just deleted all my apps manually, uninstalled, removed the folders, etc. Then grabbed latest warehouse from github, installed it, and started it. It shows that I already have an app installed called "lake". What is that? 
![image](https://user-images.githubusercontent.com/3472628/95232804-376ef300-07c2-11eb-8e5c-b518127b19a4.png)

**Comment by rfun** [comment]
So the reason this is happening is because when we search if an application is installed or not, the search is a wildcard type of search to ensure that we find the package if it is installed.  In this case it finds the `flake8` package and thinks that its the `lake` app since it contains the words `lake`
We need to either force it to search the exact name. 
Thanks for posting this issue.

**Comment by danames** [comment]
Wow! interesting side case that we may not have found had it not been for
the lake app!
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by rfun** [comment]
Fixed in version 0.2.4

**Comment by danames** [comment]
confirmed
